python3 cycle_consty_train_aug.py --scene_name alley_1 >> alley_1_train_final.txt
python3 cycle_consty_train_aug.py --scene_name ambush_4 >> ambush_4_train_final.txt
python3 cycle_consty_train_aug.py --scene_name ambush_7 >> ambush_7_train_final.txt
python3 cycle_consty_train_aug.py --scene_name bandage_1 >> bandage_1_train_final.txt
python3 cycle_consty_train_aug.py --scene_name cave_4 >> cave_4_train_final.txt
python3 cycle_consty_train_aug.py --scene_name market_6 >> market_6_train_final.txt
python3 cycle_consty_train_aug.py --scene_name shaman_3 >> shaman_3_train_final.txt
python3 cycle_consty_train_aug.py --scene_name temple_2 >> temple_2_train_final.txt
python3 cycle_consty_train_aug.py --scene_name alley_2 >> alley_2_train_final.txt
python3 cycle_consty_train_aug.py --scene_name ambush_5 >> ambush_5_train_final.txt
python3 cycle_consty_train_aug.py --scene_name bamboo_1 >> bamboo_1_train_final.txt
python3 cycle_consty_train_aug.py --scene_name bandage_2 >> bandage_2_train_final.txt
python3 cycle_consty_train_aug.py --scene_name market_2 >> market_2_train_final.txt
python3 cycle_consty_train_aug.py --scene_name mountain_1 >> mountain_1_train_final.txt
python3 cycle_consty_train_aug.py --scene_name sleeping_1 >> sleeping_1_train_final.txt
python3 cycle_consty_train_aug.py --scene_name temple_3 >> temple_3_train_final.txt
python3 cycle_consty_train_aug.py --scene_name ambush_2 >> ambush_2_train_final.txt
python3 cycle_consty_train_aug.py --scene_name ambush_6 >> ambush_6_train_final.txt
python3 cycle_consty_train_aug.py --scene_name bamboo_2 >> bamboo_2_train_final.txt
python3 cycle_consty_train_aug.py --scene_name cave_2 >> cave_2_train_final.txt
python3 cycle_consty_train_aug.py --scene_name market_5 >> market_5_train_final.txt
python3 cycle_consty_train_aug.py --scene_name shaman_2 >> shaman_2_train_final.txt
python3 cycle_consty_train_aug.py --scene_name sleeping_2 >> sleeping_2_train_final.txt
