python3 cycle_consty_train_aug.py --scene_name alley_1 --gen_data > alley_1_gendata.txt
python3 cycle_consty_train_aug.py --scene_name ambush_5 --gen_data > ambush_5_gendata.txt
python3 cycle_consty_train_aug.py --scene_name bamboo_2 --gen_data > bamboo_2_gendata.txt
python3 cycle_consty_train_aug.py --scene_name cave_4 --gen_data > cave_4_gendata.txt
python3 cycle_consty_train_aug.py --scene_name mountain_1 --gen_data > mountain_1_gendata.txt
python3 cycle_consty_train_aug.py --scene_name sleeping_2 --gen_data > sleeping_2_gendata.txt
python3 cycle_consty_train_aug.py --scene_name alley_2 --gen_data > alley_2_gendata.txt
python3 cycle_consty_train_aug.py --scene_name ambush_6 --gen_data > ambush_6_gendata.txt
python3 cycle_consty_train_aug.py --scene_name bandage_1 --gen_data > bandage_1_gendata.txt
python3 cycle_consty_train_aug.py --scene_name market_2 --gen_data > market_2_gendata.txt
python3 cycle_consty_train_aug.py --scene_name shaman_2 --gen_data > shaman_2_gendata.txt
python3 cycle_consty_train_aug.py --scene_name temple_2 --gen_data > temple_2_gendata.txt
python3 cycle_consty_train_aug.py --scene_name ambush_2 --gen_data > ambush_2_gendata.txt
python3 cycle_consty_train_aug.py --scene_name ambush_7 --gen_data > ambush_7_gendata.txt
python3 cycle_consty_train_aug.py --scene_name bandage_2 --gen_data > bandage_2_gendata.txt
python3 cycle_consty_train_aug.py --scene_name market_5 --gen_data > market_5_gendata.txt
python3 cycle_consty_train_aug.py --scene_name shaman_3 --gen_data > shaman_3_gendata.txt
python3 cycle_consty_train_aug.py --scene_name temple_3 --gen_data > temple_3_gendata.txt
python3 cycle_consty_train_aug.py --scene_name ambush_4 --gen_data > ambush_4_gendata.txt
python3 cycle_consty_train_aug.py --scene_name bamboo_1 --gen_data > bamboo_1_gendata.txt
python3 cycle_consty_train_aug.py --scene_name cave_2 --gen_data > cave_2_gendata.txt
python3 cycle_consty_train_aug.py --scene_name market_6 --gen_data > market_6_gendata.txt
python3 cycle_consty_train_aug.py --scene_name sleeping_1 --gen_data > sleeping_1_gendata.txt
